# Solve

In [6]:
import numpy as np
import pandas as pd
import json

In [59]:
VELOCIDAD_MEDIA = 20/60/60 # 20 km/h en km/s

## Funciones

In [61]:
import math
def haversine(lat1, lon1, lat2, lon2):

      R = 3959.87433 # this is in miles.  For Earth radius in kilometers use 6372.8 km

      dLat = math.radians(lat2 - lat1)
      dLon = math.radians(lon2 - lon1)
      lat1 = math.radians(lat1)
      lat2 = math.radians(lat2)

      a = math.sin(dLat/2)**2 + math.cos(lat1)*math.cos(lat2)*math.sin(dLon/2)**2
      c = 2*math.asin(math.sqrt(a))
      return R * c

## Instancia Small

### Preprocesado

In [89]:
# leer instancia 
data = json.load(open('instancias/medium.json'))
data.keys()

dict_keys(['viajes', 'vehiculos'])

In [90]:
data_viajes = pd.DataFrame(data['viajes'])
data_vehiculos = pd.DataFrame(data['vehiculos'])
# data_viajes, data_vehiculos

In [91]:
data_vehiculos['hora_inicio_jornada'] = data_vehiculos['inicio_jornada'].apply(lambda x: x['hora'])
data_vehiculos['lat_inicio_jornada'] = data_vehiculos['inicio_jornada'].apply(lambda x: x['lat'])
data_vehiculos['lon_inicio_jornada'] = data_vehiculos['inicio_jornada'].apply(lambda x: x['lon'])

data_vehiculos['hora_fin_jornada'] = data_vehiculos['fin_jornada'].apply(lambda x: x['hora'])
data_vehiculos['lat_fin_jornada'] = data_vehiculos['fin_jornada'].apply(lambda x: x['lat'])
data_vehiculos['lon_fin_jornada'] = data_vehiculos['fin_jornada'].apply(lambda x: x['lon'])

data_vehiculos.drop(columns=['inicio_jornada', 'fin_jornada'], inplace=True)
data_vehiculos

,id,capacidad,hora_inicio_jornada,lat_inicio_jornada,lon_inicio_jornada,hora_fin_jornada,lat_fin_jornada,lon_fin_jornada
0,VEH001,6,28800,-33.4489,-70.6693,54000,-33.4489,-70.6693
1,VEH002,6,28800,-33.4372,-70.6506,54000,-33.4372,-70.6506
2,VEH003,5,28800,-33.4258,-70.6106,54000,-33.4258,-70.6106
3,VEH004,6,28800,-33.4150,-70.6050,54000,-33.4150,-70.6050
4,VEH005,5,28800,-33.4320,-70.6180,54000,-33.4320,-70.6180

In [92]:
data_viajes

,id,origen,destino,hora_presentacion,num_pasajeros
0,V001,"{'lat': -33.4489, 'lon': -70.6693}","{'lat': -33.4372, 'lon': -70.6506}",28800,2
1,V002,"{'lat': -33.4258, 'lon': -70.6106}","{'lat': -33.4569, 'lon': -70.6483}",29100,3
2,V003,"{'lat': -33.415, 'lon': -70.605}","{'lat': -33.4489, 'lon': -70.6693}",29700,4
3,V004,"{'lat': -33.432, 'lon': -70.618}","{'lat': -33.445, 'lon': -70.66}",30300,1
4,V005,"{'lat': -33.45, 'lon': -70.67}","{'lat': -33.428, 'lon': -70.615}",30900,5
5,V006,"{'lat': -33.44, 'lon': -70.654}","{'lat': -33.42, 'lon': -70.61}",31500,2
6,V007,"{'lat': -33.41, 'lon': -70.6}","{'lat': -33.455, 'lon': -70.675}",32100,3
7,V008,"{'lat': -33.438, 'lon': -70.652}","{'lat': -33.418, 'lon': -70.608}",32700,4
8,V009,"{'lat': -33.447, 'lon': -70.665}","{'lat': -33.43, 'lon': -70.62}",33300,2
9,V010,"{'lat': -33.422, 'lon': -70.613}","{'lat': -33.451, 'lon': -70.668}",33900,3
10,V011,"{'lat': -33.435, 'lon': -70.625}","{'lat': -33.442, 'lon': -70.658}",34500,1
11,V012,"{'lat': -33.453, 'lon': -70.672}","{'lat': -33.417, 'lon': -70.607}",35100,5
12,V013,"{'lat': -33.429, 'lon': -70.617}","{'lat': -33.446, 'lon': -70.662}",35700,2
13,V014,"{'lat': -33.441, 'lon': -70.656}","{'lat': -33.424, 'lon': -70.612}",36300,4
14,V015,"{'lat': -33.412, 'lon': -70.602}","{'lat': -33.448, 'lon': -70.667}",36900,3
15,V016,"{'lat': -33.436, 'lon': -70.63}","{'lat': -33.419, 'lon': -70.609}",37500,2
16,V017,"{'lat': -33.444, 'lon': -70.661}","{'lat': -33.427, 'lon': -70.616}",38100,1
17,V018,"{'lat': -33.452, 'lon': -70.671}","{'lat': -33.416, 'lon': -70.606}",38700,4
18,V019,"{'lat': -33.425, 'lon': -70.614}","{'lat': -33.449, 'lon': -70.669}",39300,3
19,V020,"{'lat': -33.439, 'lon': -70.653}","{'lat': -33.421, 'lon': -70.611}",39900,5
20,V021,"{'lat': -33.413, 'lon': -70.603}","{'lat': -33.447, 'lon': -70.664}",40500,2
21,V022,"{'lat': -33.434, 'lon': -70.628}","{'lat': -33.443, 'lon': -70.659}",41100,3
22,V023,"{'lat': -33.45, 'lon': -70.67}","{'lat': -33.423, 'lon': -70.613}",41700,4
23,V024,"{'lat': -33.426, 'lon': -70.615}","{'lat': -33.454, 'lon': -70.673}",42300,1
24,V025,"{'lat': -33.437, 'lon': -70.651}","{'lat': -33.418, 'lon': -70.608}",42900,2
25,V026,"{'lat': -33.445, 'lon': -70.663}","{'lat': -33.429, 'lon': -70.619}",43500,3
26,V027,"{'lat': -33.411, 'lon': -70.601}","{'lat': -33.452, 'lon': -70.671}",44100,4
27,V028,"{'lat': -33.433, 'lon': -70.627}","{'lat': -33.42, 'lon': -70.61}",44700,5
28,V029,"{'lat': -33.448, 'lon': -70.666}","{'lat': -33.425, 'lon': -70.614}",45300,2
29,V030,"{'lat': -33.414, 'lon': -70.604}","{'lat': -33.441, 'lon': -70.656}",45900,3

In [93]:
data_viajes['lat_origen'] = data_viajes['origen'].apply(lambda x: x['lat'])
data_viajes['lon_origen'] = data_viajes['origen'].apply(lambda x: x['lon'])

data_viajes['lat_destino'] = data_viajes['destino'].apply(lambda x: x['lat'])
data_viajes['lon_destino'] = data_viajes['destino'].apply(lambda x: x['lon'])

data_viajes.drop(columns=['origen', 'destino'], inplace=True)
data_viajes

,id,hora_presentacion,num_pasajeros,lat_origen,lon_origen,lat_destino,lon_destino
0,V001,28800,2,-33.4489,-70.6693,-33.4372,-70.6506
1,V002,29100,3,-33.4258,-70.6106,-33.4569,-70.6483
2,V003,29700,4,-33.4150,-70.6050,-33.4489,-70.6693
3,V004,30300,1,-33.4320,-70.6180,-33.4450,-70.6600
4,V005,30900,5,-33.4500,-70.6700,-33.4280,-70.6150
5,V006,31500,2,-33.4400,-70.6540,-33.4200,-70.6100
6,V007,32100,3,-33.4100,-70.6000,-33.4550,-70.6750
7,V008,32700,4,-33.4380,-70.6520,-33.4180,-70.6080
8,V009,33300,2,-33.4470,-70.6650,-33.4300,-70.6200
9,V010,33900,3,-33.4220,-70.6130,-33.4510,-70.6680
10,V011,34500,1,-33.4350,-70.6250,-33.4420,-70.6580
11,V012,35100,5,-33.4530,-70.6720,-33.4170,-70.6070
12,V013,35700,2,-33.4290,-70.6170,-33.4460,-70.6620
13,V014,36300,4,-33.4410,-70.6560,-33.4240,-70.6120
14,V015,36900,3,-33.4120,-70.6020,-33.4480,-70.6670
15,V016,37500,2,-33.4360,-70.6300,-33.4190,-70.6090
16,V017,38100,1,-33.4440,-70.6610,-33.4270,-70.6160
17,V018,38700,4,-33.4520,-70.6710,-33.4160,-70.6060
18,V019,39300,3,-33.4250,-70.6140,-33.4490,-70.6690
19,V020,39900,5,-33.4390,-70.6530,-33.4210,-70.6110
20,V021,40500,2,-33.4130,-70.6030,-33.4470,-70.6640
21,V022,41100,3,-33.4340,-70.6280,-33.4430,-70.6590
22,V023,41700,4,-33.4500,-70.6700,-33.4230,-70.6130
23,V024,42300,1,-33.4260,-70.6150,-33.4540,-70.6730
24,V025,42900,2,-33.4370,-70.6510,-33.4180,-70.6080
25,V026,43500,3,-33.4450,-70.6630,-33.4290,-70.6190
26,V027,44100,4,-33.4110,-70.6010,-33.4520,-70.6710
27,V028,44700,5,-33.4330,-70.6270,-33.4200,-70.6100
28,V029,45300,2,-33.4480,-70.6660,-33.4250,-70.6140
29,V030,45900,3,-33.4140,-70.6040,-33.4410,-70.6560

In [94]:
data_viajes['tiempo_en_ruta'] = data_viajes.apply(lambda x: haversine(x['lat_origen'], x['lon_origen'], x['lat_destino'], x['lon_destino']) / VELOCIDAD_MEDIA, axis=1)
data_viajes['hora_finalizacion'] = data_viajes['hora_presentacion'] + data_viajes['tiempo_en_ruta']

### Prototipo

In [95]:
# def heuristica_solucion(data_viajes, data_vehiculos):
ids_veh = data_vehiculos['id']
# early_veh = {row['id']: row['hora_inicio_jornada'] for _, row in data_vehiculos.iterrows()}
# late_veh = {row['id']: row['hora_fin_jornada'] for _, row in data_vehiculos.iterrows()}
cap_veh = {row['id']: row['capacidad'] for _, row in data_vehiculos.iterrows()}
# Inicializo hora libre de cada vehículo con su hora de inicio de jornada
hora_libre = {vehiculo.id: vehiculo.hora_inicio_jornada for vehiculo in data_vehiculos.itertuples()}
ubicacion_libre = {row['id']: (row['lat_inicio_jornada'], row['lon_inicio_jornada']) for _, row in data_vehiculos.iterrows()}

sorted_viajes = data_viajes.sort_values(by='hora_presentacion')

In [96]:
viajes_no_asignados = []
rutas = {vehiculo.id: [] for vehiculo in data_vehiculos.itertuples()}
for viaje in sorted_viajes.itertuples():
    sin_asignar = True
    
    # Revisar si hay algún vehículo disponible en la ubicación del viaje a la hora de presentación

    # Asignar el viaje al vehículo más temprano disponible
    candidatos = []
    for vehiculo in data_vehiculos.itertuples():

        # Checkeo -1: hora de presentación mayor a inicio de ventana operativa
        if not(vehiculo.hora_inicio_jornada <= viaje.hora_presentacion):
            print("Hora de presentacion previa al inicio de la jornada")
            continue
        # Checkeo 0: que el vehículo tenga capacidad para la cantidad de pasajeros del viaje
        if not(cap_veh[vehiculo.id] >= viaje.num_pasajeros):
            print(f"El vehículo {vehiculo.id} no tiene capacidad para el viaje {viaje.id} \n{vehiculo.capacidad} < {viaje.num_pasajeros}")
            continue
            
        # Checkeo 1: que llegue a la hora de presentacion
        dh = haversine(ubicacion_libre[vehiculo.id][0], ubicacion_libre[vehiculo.id][1], viaje.lat_origen, viaje.lon_origen)
        tiempo_llegada = dh / VELOCIDAD_MEDIA
        hora_minima_llegada = hora_libre[vehiculo.id] + tiempo_llegada #type:ignore
        if not(hora_minima_llegada <= viaje.hora_presentacion): # type:ignore
            print(f"El vehículo {vehiculo.id} no llega a la hora de presentacion de {viaje.id}: {hora_libre[vehiculo.id]} + {tiempo_llegada} > {viaje.hora_presentacion}")
            continue
        
        # Checkeo 2: que el viaje + su retorno termine antes de la hora de fin de jornada del vehículo    
        hl = viaje.hora_presentacion + viaje.tiempo_en_ruta # type:ignore
        dh_retorno = haversine(viaje.lat_destino, viaje.lon_destino, vehiculo.lat_fin_jornada, vehiculo.lon_fin_jornada) 
        tiempo_viaje = dh_retorno / VELOCIDAD_MEDIA
        if not(hora_libre[vehiculo.id] + tiempo_llegada + tiempo_viaje <= vehiculo.hora_fin_jornada): # type:ignore
            continue
        
        espera = viaje.hora_presentacion - hora_minima_llegada
        candidatos.append((vehiculo.id, espera))
    print(viaje.id, candidatos)
    sorted_candidatos = sorted(candidatos, key=lambda x: x[1])
    vehiculo_asignado = sorted_candidatos[0][0] if len(sorted_candidatos) > 0 else None
    print(f"Viaje {viaje.id} asignado a vehículo {vehiculo_asignado}")

    # Actualizar hora libre y ubicación libre del vehículo asignado
    if vehiculo_asignado is not None:
        hora_libre[vehiculo_asignado] = viaje.hora_finalizacion # type:ignore
        ubicacion_libre[vehiculo_asignado] = (viaje.lat_destino, viaje.lon_destino)
        rutas[vehiculo_asignado].append(viaje.id)
    else:
        print(f"Viaje {viaje.id} no pudo ser asignado a ningún vehículo.")
        viajes_no_asignados.append(viaje.id)
    
print()
print("Viajes no asignados:", viajes_no_asignados)
print("Rutas asignadas a vehículos:", rutas)

El vehículo VEH002 no llega a la hora de presentacion de V001: 28800 + 242.62506097776435 > 28800
El vehículo VEH003 no llega a la hora de presentacion de V001: 28800 + 673.7426099949986 > 28800
El vehículo VEH004 no llega a la hora de presentacion de V001: 28800 + 789.6129379185406 > 28800
El vehículo VEH005 no llega a la hora de presentacion de V001: 28800 + 572.5400359260938 > 28800
V001 [('VEH001', 0.0)]
Viaje V001 asignado a vehículo VEH001
El vehículo VEH001 no llega a la hora de presentacion de V002: 29042.625060977763 + 438.82833757408116 > 29100
El vehículo VEH002 no llega a la hora de presentacion de V002: 28800 + 438.82833757408116 > 29100
V002 [('VEH003', 300.0), ('VEH004', 153.60192051346166), ('VEH005', 191.13430598449122)]
Viaje V002 asignado a vehículo VEH004
El vehículo VEH004 no llega a la hora de presentacion de V003: 29650.315411900578 + 688.3070970648585 > 29700
V003 [('VEH001', 109.2633891334408), ('VEH002', 351.8884501112043), ('VEH003', 753.6019205134617), ('VEH005', 649.1111433521)]
Viaje V003 asignado a vehículo VEH001
El vehículo VEH001 no llega a la hora de presentacion de V004: 30489.61293791854 + 572.5400359260938 > 30300
V004 [('VEH002', 1155.431917843085), ('VEH003', 1391.1343059844912), ('VEH004', 208.23100920990692), ('VEH005', 1500.0)]
Viaje V004 asignado a vehículo VEH004
V005 [('VEH001', 394.8933691767452), ('VEH002', 1843.2684069487877), ('VEH003', 1413.78867731032), ('VEH004', 13.953099151007336), ('VEH005', 1515.5925387969655)]
Viaje V005 asignado a vehículo VEH004
El vehículo VEH004 no llega a la hora de presentacion de V006: 31533.1671495347 + 431.5305600080282 > 31500
V006 [('VEH001', 816.7824879431864), ('VEH002', 2650.4103755239266), ('VEH003', 2216.036325960322), ('VEH005', 2313.2431830078567)]
Viaje V006 asignado a vehículo VEH001
El vehículo VEH001 no llega a la hora de presentacion de V007: 32020.17819819466 + 162.045764147772 > 32100
V007 [('VEH002', 2675.0842350050916), ('VEH003', 3074.7240537071557), ('VEH004', 294.06645476835183), ('VEH005', 2968.585458770256)]
Viaje V007 asignado a vehículo VEH004
El vehículo VEH004 no llega a la hora de presentacion de V008: 33058.99618639525 + 318.9437121221008 > 32700
V008 [('VEH001', 189.62994916590833), ('VEH002', 3882.3852889526606), ('VEH003', 3444.177898468606), ('VEH005', 3539.2203988252477)]
Viaje V008 asignado a vehículo VEH001
El vehículo VEH001 no llega a la hora de presentacion de V009: 33220.18744213034 + 693.0676564226898 > 33300
V009 [('VEH002', 4307.105425662998), ('VEH003', 3876.7044410871713), ('VEH004', 97.20367964887555), ('VEH005', 3977.624105511073)]
Viaje V009 asignado a vehículo VEH004
El vehículo VEH004 no llega a la hora de presentacion de V010: 33812.79369522275 + 123.23517543268446 > 33900
V010 [('VEH001', 607.8991048036987), ('VEH002', 4666.241767598283), ('VEH003', 5046.561157060627), ('VEH005', 4965.1999080878595)]
Viaje V010 asignado a vehículo VEH001
El vehículo VEH001 no llega a la hora de presentacion de V011: 34575.40300978236 + 488.735422078215 > 34500
V011 [('VEH002', 5432.829344409653), ('VEH003', 5511.718126835582), ('VEH004', 606.1901281315149), ('VEH005', 5618.304708798747)]
Viaje V011 asignado a vehículo VEH004
V012 [('VEH001', 476.1944500071477), ('VEH002', 6003.384406652105), ('VEH003', 5578.353705697144), ('VEH004', 46.91626587614155), ('VEH005', 5681.555248783592)]
Viaje V012 asignado a vehículo VEH004
El vehículo VEH004 no llega a la hora de presentacion de V013: 35909.89481077313 + 181.84153271350348 > 35700
V013 [('VEH001', 528.6097119302358), ('VEH002', 6536.5612892212885), ('VEH003', 6822.539776903635), ('VEH005', 6861.261895697586)]
Viaje V013 asignado a vehículo VEH001
El vehículo VEH001 no llega a la hora de presentacion de V014: 36212.798599964284 + 88.02417480659597 > 36300
El vehículo VEH004 no llega a la hora de presentacion de V014: 35909.89481077313 + 589.8741536971409 > 36300
V014 [('VEH002', 7426.670319535024), ('VEH003', 6992.151175342977), ('VEH005', 7089.92604133645)]
Viaje V014 asignado a vehículo VEH003
El vehículo VEH001 no llega a la hora de presentacion de V015: 36212.798599964284 + 752.964733204749 > 36900
El vehículo VEH003 no llega a la hora de presentacion de V015: 36803.38337869491 + 181.84494696329313 > 36900
V015 [('VEH002', 7505.940883939042), ('VEH004', 909.0821155182784), ('VEH005', 7800.828159955832)]
Viaje V015 asignado a vehículo VEH004
El vehículo VEH004 no llega a la hora de presentacion de V016: 37709.9272044084 + 412.078752115006 > 37500
V016 [('VEH001', 932.483501832714), ('VEH002', 8485.62293080823), ('VEH003', 457.4315623715447), ('VEH005', 8565.849096249316)]
Viaje V016 asignado a vehículo VEH003
El vehículo VEH003 no llega a la hora de presentacion de V017: 37803.749931084494 + 623.0401720071203 > 38100
V017 [('VEH001', 1860.242210884855), ('VEH002', 9162.843704618703), ('VEH004', 310.3534160446725), ('VEH005', 8829.30688619539)]
Viaje V017 asignado a vehículo VEH004
El vehículo VEH004 no llega a la hora de presentacion de V018: 38612.808409087374 + 650.1678489540855 > 38700
V018 [('VEH001', 2367.6248551406898), ('VEH002', 9619.390682904632), ('VEH003', 132.81958600201324), ('VEH005', 9296.177168673865)]
Viaje V018 asignado a vehículo VEH003
El vehículo VEH003 no llega a la hora de presentacion de V019: 39509.9012897972 + 139.41205141740386 > 39300
V019 [('VEH001', 2524.559686936125), ('VEH002', 10090.82795527681), ('VEH004', 654.7841238900728), ('VEH005', 10403.522016104482)]
Viaje V019 asignado a vehículo VEH004
El vehículo VEH003 no llega a la hora de presentacion de V020: 39509.9012897972 + 565.6764707462082 > 39900
El vehículo VEH004 no llega a la hora de presentacion de V020: 39944.32422877721 + 207.51238874101278 > 39900
V020 [('VEH001', 3559.483915521705), ('VEH002', 11066.501052441788), ('VEH005', 10726.357219206591)]
Viaje V020 asignado a vehículo VEH001
El vehículo VEH001 no llega a la hora de presentacion de V021: 40390.18738358877 + 129.63538541797251 > 40500
El vehículo VEH004 no llega a la hora de presentacion de V021: 39944.32422877721 + 818.5912918043938 > 40500
V021 [('VEH002', 11121.305302967645), ('VEH003', 941.4848659670606), ('VEH005', 11416.935128685218)]
Viaje V021 asignado a vehículo VEH003
El vehículo VEH003 no llega a la hora de presentacion de V022: 41261.57041533067 + 407.205465047655 > 41100
V022 [('VEH001', 470.4223863132938), ('VEH002', 12062.02456357007), ('VEH004', 690.9524831186791), ('VEH005', 12193.242010782731)]
Viaje V022 asignado a vehículo VEH001
V023 [('VEH001', 115.66386209451593), ('VEH002', 12643.268406948788), ('VEH003', 365.8236185092828), ('VEH004', 1739.473839114762), ('VEH005', 12315.592538796966)]
Viaje V023 asignado a vehículo VEH001
El vehículo VEH001 no llega a la hora de presentacion de V024: 42380.424297279234 + 42.70908154717171 > 42300
V024 [('VEH002', 13105.01068991069), ('VEH003', 466.57819983270747), ('VEH004', 1726.2878718965367), ('VEH005', 13419.120221207144)]
Viaje V024 asignado a vehículo VEH003
El vehículo VEH003 no llega a la hora de presentacion de V025: 42995.596007636654 + 311.2516713445167 > 42900
V025 [('VEH001', 88.31995323174488), ('VEH002', 14095.159134207337), ('VEH004', 2716.5125848838215), ('VEH005', 13751.80490827413)]
Viaje V025 asignado a vehículo VEH001
El vehículo VEH001 no llega a la hora de presentacion de V026: 43405.1568514188 + 662.4753009344149 > 43500
V026 [('VEH002', 14538.800797124008), ('VEH003', 351.72853787068743), ('VEH004', 3475.9569526346604), ('VEH005', 14205.645864218386)]
Viaje V026 asignado a vehículo VEH003
El vehículo VEH003 no llega a la hora de presentacion de V027: 43998.26304401017 + 291.67547832783833 > 44100
V027 [('VEH001', 581.4108454261659), ('VEH002', 14690.532786320731), ('VEH004', 3306.0318280583742), ('VEH005', 14984.711117150258)]
Viaje V027 asignado a vehículo VEH001
El vehículo VEH001 no llega a la hora de presentacion de V028: 44987.86539365061 + 514.2854770493188 > 44700
V028 [('VEH002', 15649.485579887863), ('VEH003', 604.9146322854649), ('VEH004', 4276.39328705705), ('VEH005', 15805.73854216035)]
Viaje V028 asignado a vehículo VEH003
El vehículo VEH003 no llega a la hora de presentacion de V029: 44939.39172928097 + 677.7390091166334 > 45300
V029 [('VEH001', 240.2341073651187), ('VEH002', 16291.176287121089), ('VEH004', 5322.142878794613), ('VEH005', 15963.428390074798)]
Viaje V029 asignado a vehículo VEH001
El vehículo VEH001 no llega a la hora de presentacion de V030: 45910.97330852397 + 171.7780569357086 > 45900
V030 [('VEH002', 16536.62247639552), ('VEH003', 863.3817316185887), ('VEH004', 5152.5703732608745), ('VEH005', 16833.030213894992)]
Viaje V030 asignado a vehículo VEH003

Viajes no asignados: []
Rutas asignadas a vehículos: {'VEH001': ['V001', 'V003', 'V006', 'V008', 'V010', 'V013', 'V020', 'V022', 'V023', 'V025', 'V027', 'V029'], 'VEH002': [], 'VEH003': ['V014', 'V016', 'V018', 'V021', 'V024', 'V026', 'V028', 'V030'], 'VEH004': ['V002', 'V004', 'V005', 'V007', 'V009', 'V011', 'V012', 'V015', 'V017', 'V019'], 'VEH005': []}

## Heurística

In [99]:
def heuristica_solucion(data_viajes, data_vehiculos, verbose = False):
    ids_veh = data_vehiculos['id']
    # early_veh = {row['id']: row['hora_inicio_jornada'] for _, row in data_vehiculos.iterrows()}
    # late_veh = {row['id']: row['hora_fin_jornada'] for _, row in data_vehiculos.iterrows()}
    cap_veh = {row['id']: row['capacidad'] for _, row in data_vehiculos.iterrows()}
    # Inicializo hora libre de cada vehículo con su hora de inicio de jornada
    hora_libre = {vehiculo.id: vehiculo.hora_inicio_jornada for vehiculo in data_vehiculos.itertuples()}
    ubicacion_libre = {row['id']: (row['lat_inicio_jornada'], row['lon_inicio_jornada']) for _, row in data_vehiculos.iterrows()}

    sorted_viajes = data_viajes.sort_values(by='hora_presentacion')

    viajes_no_asignados = []
    rutas = {vehiculo.id: [] for vehiculo in data_vehiculos.itertuples()}
    for viaje in sorted_viajes.itertuples():
        sin_asignar = True
        
        # Revisar si hay algún vehículo disponible en la ubicación del viaje a la hora de presentación

        # Asignar el viaje al vehículo más temprano disponible
        candidatos = []
        for vehiculo in data_vehiculos.itertuples():

            # Checkeo -1: hora de presentación mayor a inicio de ventana operativa
            if not(vehiculo.hora_inicio_jornada <= viaje.hora_presentacion):
                if verbose: print("Hora de presentacion previa al inicio de la jornada")
                continue
            # Checkeo 0: que el vehículo tenga capacidad para la cantidad de pasajeros del viaje
            if not(cap_veh[vehiculo.id] >= viaje.num_pasajeros):
                if verbose: print(f"El vehículo {vehiculo.id} no tiene capacidad para el viaje {viaje.id} \n{vehiculo.capacidad} < {viaje.num_pasajeros}")
                continue
                
            # Checkeo 1: que llegue a la hora de presentacion
            dh = haversine(ubicacion_libre[vehiculo.id][0], ubicacion_libre[vehiculo.id][1], viaje.lat_origen, viaje.lon_origen)
            tiempo_llegada = dh / VELOCIDAD_MEDIA
            hora_minima_llegada = hora_libre[vehiculo.id] + tiempo_llegada #type:ignore
            if not(hora_minima_llegada <= viaje.hora_presentacion): # type:ignore
                if verbose: print(f"El vehículo {vehiculo.id} no llega a la hora de presentacion de {viaje.id}: {hora_libre[vehiculo.id]} + {tiempo_llegada} > {viaje.hora_presentacion}")
                continue
            
            # Checkeo 2: que el viaje + su retorno termine antes de la hora de fin de jornada del vehículo    
            hl = viaje.hora_presentacion + viaje.tiempo_en_ruta # type:ignore
            dh_retorno = haversine(viaje.lat_destino, viaje.lon_destino, vehiculo.lat_fin_jornada, vehiculo.lon_fin_jornada) 
            tiempo_viaje = dh_retorno / VELOCIDAD_MEDIA
            if not(hora_libre[vehiculo.id] + tiempo_llegada + tiempo_viaje <= vehiculo.hora_fin_jornada): # type:ignore
                continue
            
            espera = viaje.hora_presentacion - hora_minima_llegada
            candidatos.append((vehiculo.id, espera))
        if verbose: print(viaje.id, candidatos)
        sorted_candidatos = sorted(candidatos, key=lambda x: x[1])
        vehiculo_asignado = sorted_candidatos[0][0] if len(sorted_candidatos) > 0 else None
        if verbose: print(f"Viaje {viaje.id} asignado a vehículo {vehiculo_asignado}")

        # Actualizar hora libre y ubicación libre del vehículo asignado
        if vehiculo_asignado is not None:
            hora_libre[vehiculo_asignado] = viaje.hora_finalizacion # type:ignore
            ubicacion_libre[vehiculo_asignado] = (viaje.lat_destino, viaje.lon_destino)
            rutas[vehiculo_asignado].append(viaje.id)
        else:
            if verbose: print(f"Viaje {viaje.id} no pudo ser asignado a ningún vehículo.")
            viajes_no_asignados.append(viaje.id)
        
    if verbose: print()
    print("Viajes no asignados:", viajes_no_asignados)
    print("Rutas asignadas a vehículos:", rutas)
    return rutas, viajes_no_asignados

### Resolver

In [103]:
rutas_generadas, viajes_no_asignados = heuristica_solucion(data_viajes, data_vehiculos, verbose=False)

Viajes no asignados: []
Rutas asignadas a vehículos: {'VEH001': ['V001', 'V003', 'V006', 'V008', 'V010', 'V013', 'V020', 'V022', 'V023', 'V025', 'V027', 'V029'], 'VEH002': [], 'VEH003': ['V014', 'V016', 'V018', 'V021', 'V024', 'V026', 'V028', 'V030'], 'VEH004': ['V002', 'V004', 'V005', 'V007', 'V009', 'V011', 'V012', 'V015', 'V017', 'V019'], 'VEH005': []}

### Validacion

In [122]:
rutas = rutas_generadas
verbose = False

for veh, ruta in rutas.items():
    print(f"Vehículo {veh}: {ruta}")
    if ruta == []:
        print(f"Vehículo {veh} no tiene viajes asignados.")
        continue
    
    vehiculo = data_vehiculos[data_vehiculos['id'] == veh].iloc[0]
    # === Checkeo de factiblidad de las rutas asignadas ===
    
    # Criterio 1: que cada viaje asignado a un vehículo cumpla con las restricciones de capacidad
    for idx, viaje_id in enumerate(ruta):
        viaje = data_viajes[data_viajes['id'] == viaje_id].iloc[0]
        if vehiculo.capacidad < viaje.num_pasajeros:
            print(f"Error: Vehículo {veh} no tiene capacidad para el viaje {viaje_id}")
        else:
            if verbose: print(f"Vehículo {veh} tiene capacidad {vehiculo.capacidad} para el viaje {viaje_id} con {viaje.num_pasajeros} pasajeros")
    
    # Criterio 2: sucesión de viajes --> fin viaje i + deadhead i,j <= hora presentación viaje j
        viaje_siguiente = data_viajes[data_viajes['id'] == ruta[idx+1]].iloc[0] if idx + 1 < len(ruta) else None
        if viaje_siguiente is not None:
            dh = haversine(viaje.lat_destino, viaje.lon_destino, viaje_siguiente.lat_origen, viaje_siguiente.lon_origen)
            tiempo_llegada = dh / VELOCIDAD_MEDIA
            hora_llegada = viaje.hora_finalizacion + tiempo_llegada
            if not(hora_llegada <= viaje_siguiente.hora_presentacion):
                print(f"Error: Vehículo {veh} no llega a tiempo para el viaje {viaje_siguiente.id} después de completar el viaje {viaje_id}")
            else:
                if verbose: print(f"Vehículo {veh} llega a tiempo para el viaje {viaje_siguiente.id} después de completar el viaje {viaje_id}")
    
    # Criterio 3: primer viaje i - deadhead depot,i despues de inicio de ventana operativa
    primer_viaje = data_viajes[data_viajes['id'] == ruta[0]].iloc[0]
    dh = haversine(vehiculo.lat_inicio_jornada, vehiculo.lon_inicio_jornada, primer_viaje.lat_origen, primer_viaje.lon_origen)
    tiempo_llegada = dh / VELOCIDAD_MEDIA   

    hora_llegada = vehiculo.hora_inicio_jornada + tiempo_llegada
    if not(hora_llegada <= primer_viaje.hora_presentacion):
        print(f"Error: Vehículo {veh} no llega a tiempo para el primer viaje {primer_viaje.id} después de salir del depósito: {vehiculo.hora_inicio_jornada} + {tiempo_llegada} > {primer_viaje.hora_presentacion}")
    else:
        if verbose: print(f"Vehículo {veh} llega a tiempo para el primer viaje {primer_viaje.id} después de salir del depósito")
    # Criterio 4: fin viaje i + deadhead i, depot antes de fin de ventana operativa
    ultimo_viaje = data_viajes[data_viajes['id'] == ruta[-1]].iloc[0]
    dh = haversine(ultimo_viaje.lat_destino, ultimo_viaje.lon_destino, vehiculo.lat_fin_jornada, vehiculo.lon_fin_jornada)
    tiempo_llegada = dh / VELOCIDAD_MEDIA   
    hora_llegada = ultimo_viaje.hora_finalizacion + tiempo_llegada
    if not(hora_llegada <= vehiculo.hora_fin_jornada):
        print(f"Error: Vehículo {veh} no llega a tiempo al depósito después de completar el último viaje {ultimo_viaje.id}: {ultimo_viaje.hora_finalizacion} + {tiempo_llegada} > {vehiculo.hora_fin_jornada}")
    else:
        if verbose: print(f"Vehículo {veh} llega a tiempo para el ultimo viaje {ultimo_viaje.id} después de salir del depósito")

Vehículo VEH001: ['V001', 'V003', 'V006', 'V008', 'V010', 'V013', 'V020', 'V022', 'V023', 'V025', 'V027', 'V029']
Vehículo VEH002: []
Vehículo VEH002 no tiene viajes asignados.
Vehículo VEH003: ['V014', 'V016', 'V018', 'V021', 'V024', 'V026', 'V028', 'V030']
Vehículo VEH004: ['V002', 'V004', 'V005', 'V007', 'V009', 'V011', 'V012', 'V015', 'V017', 'V019']
Vehículo VEH005: []
Vehículo VEH005 no tiene viajes asignados.

In [ ]:
def validacion_de_rutas(rutas: dict, data_viajes: dict, data_vehiculos:dict):
    for ruta in rutas.values():